name: Build

on:
  push:
    branches: [ fabric ]
    paths:
    - 'gradle/**'
    - 'src/**'
    - 'build.gradle'
    - 'settings.gradle'
    - 'gradle.properties'
    - '.github/workflows/build.yml'
  pull_request:
    branches: [ fabric ]

env:
  ARTIFACT_NAME: discord-relay

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Build project
        uses: gradle/gradle-build-action@v2
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: build
          cache-disabled: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./build/libs/*.jar
